import type { Metadata } from "next";
import localFont from "next/font/local";
import { Outfit, Inter } from "next/font/google";

import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const georgia = localFont({
  src: "./fonts/georgia.ttf",
  variable: "--font-georgia",
});

const outfit = Outfit({
  subsets: ["latin"],
  weight: ["100", "400", "500"],
  variable: "--font-outfit",
});

const inter = Inter({
  subsets: ["latin"],
  weight: ["100", "400", "500"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${outfit.variable} ${georgia.variable} ${inter.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
