import type { Metadata } from "next";
import localFont from "next/font/local";
import { Inter } from "next/font/google";
import NavBar from "@/components/NavBar";
import ScaleProvider from "@/components/scaleProvider";
import Footer from "@/components/Footer";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const georgia = localFont({
  src: "./fonts/georgia.ttf",
  variable: "--font-georgia",
});

const inter = Inter({
  subsets: ["latin"],
  weight: ["100", "400", "500"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Law Decoded",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${georgia.variable} ${inter.variable}  antialiased`}
      >
        <NavBar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
